baseURL = "https://luyas.github.io/"
languageCode = "zh-TW"
title = "LuYa'a Space"
theme = "personal-web"
copyright="© LuYa & Vishnu"
googleAnalytics = "G-3JBSEQ3MW9"
enableEmoji=true
enableRobotsTXT=true
pygmentsUseClasses=true
pygmentsCodeFences=true

[params.intro]
  main = "Hi, We're TFamily :family:"
  sub = "我們這一家!"

[params.main]
  latestPublishHeader = "最近一次的全家出遊"

[taxonomies]
  design = "designs"
  tech = "techs"

[blackfriday]
  hrefTargetBlank = true

[params]
  breadcrumb = true
  accentColor = "#FD3519"
  mainSections = ['portfolio'] # values: ['post', 'portfolio'] only accept one section, to be displayed bellow 404

[params.notFound]
  gopher = "/images/gopher.png" # checkout https://gopherize.me/
  h1 = 'Bummer!'
  p = "It seems that this page doesn't exist."

[params.sections]
  # Define how your sections will be called
  # when automatically pulled. For instance in the 404 page
  post = "article"
  portfolio = "project"
  knitting = "knitting"

[params.sidebar]
  backgroundImage = '/imgs/leftcover.png' # header background image - default "/images/default_sidebar.jpg" - Photo by Tim Marshall on Unsplash
  gradientOverlay = '' # default: rgba(0,0,0,0.4),rgba(0,0,0,0.4)
  logo = "/imgs/avatar.jpg" # - default "/images/edna-west.jpg"
[params.assets]
  favicon = "/imgs/lov.ico"
  customCSS = ""

[params.social]
  github = "https://github.com/luyas"

[params.contact]
  email = "sammi150227@gmail.com"
  text= "" # text of the contact link in the sidebar. If email params.contact.email is defined


[menu]

[[menu.main]]
  identifier = "關於LuYa"
  name = "關於LuYa"
  title = "About section"
  url = "/about/"
  weight = -120

[[menu.main]]
  identifier = "關於Vishnu"
  name = "關於Vishnu"
  title = "Vishnu"
  url = "https://vishnucho.github.io/"
  weight = -115
  
[[menu.main]]
  identifier = "portfolio"
  name = "旅遊專案列表"
  title = "Portfolio"
  url = "/portfolio/"
  weight = -110

[[menu.main]]
  identifier = "fabric"
  name = "編織小物列表"
  title = "Fabric"
  url = "/fabric/"
  weight = -100



[sitemap]
  changefreq = "monthly"
  filename = "sitemap.xml"
  priority = 0.5

[privacy]
  [privacy.googleAnalytics]
    anonymizeIP = true
    disable = true
    respectDoNotTrack = true
    useSessionStorage = false
  [privacy.twitter]
    disable = false
    enableDNT = true
    simple = false

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true